### ISSUE TITLE
TypeError: 'coo_matrix' object has no attribute '__getitem__'

### ISSUE THREAD

**Issue by jasonwbw** [balikasg/SemEval2016-Twitter_Sentiment_Evaluation#1]
I run you code, but get the error like these, have you met before? (when createDataMatrix() for training data, I have change some code, so you can ignore the line number)

Traceback (most recent call last):
  File "sa.py", line 55, in <module>
    different_pos_tags, pos_text, voca_clusters)  # Combine all  features (train)
  File "/usr/lib64/python2.7/site-packages/scipy/sparse/base.py", line 127, in **iter**
    yield self[r,:]
TypeError: 'coo_matrix' object has no attribute '**getitem**'

**Comment by jasonwbw** [comment]
It's my fault, ignore it pls.
