### ISSUE TITLE
Executing the SemEval-2016-Twitter-Sentiment-Evaluation code

### ISSUE THREAD

**Issue by AnilB87** [balikasg/SemEval2016-Twitter_Sentiment_Evaluation#2]
Hi,

I was wondering if you could make the code concerning semeval 2016 task 4, subtask B available. I'm interested in comparing your system with other sentiment classification systems. Please explain how the feature extraction module is called by the module which does sentiment classification.

**Comment by balikasg** [comment]
Hello, thanks for letting me know. I am refactoring the code and I will make it available, hopefully soon

**Comment by nishalpattan** [comment]
Hi,

When I executed the command, I am facing the error
 nishal@nishal:~SemEval_Task4/SemEval2016-Twitter_Sentiment_Evaluation/src/subtaskD$  **python phaseD.py 0.8**

Do I need to refactor the code?

Error:
=====
/usr/local/lib/python2.7/dist-packages/sklearn/cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
Traceback (most recent call last):
  File "phaseD.py", line 41, in <module>
    pos1, pos_features1, different_pos_tags1, pos_text1 = get_pos_tags_and_hashtags(tweetText+tweetTest) #Get POS of everything
  File "/home/nishal/ALL_FILES_HERE/CS_COURSES/NLP/SemEval_Task4/SemEval2016-Twitter_Sentiment_Evaluation/src/subtaskD/my_utils.py", line 414, in get_pos_tags_and_hashtags
    op= subprocess.check_output(com.split())
  File "/usr/lib/python2.7/subprocess.py", line 567, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 13] Permission denied

Thanks
Nishal
